# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial